# Make /admin load its index.html (no 404s on refresh)
[[redirects]]
from = "/admin"
to = "/admin/index.html"
status = 200

# SPA fallback so deep links like /welcome or /?preview=1 work
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# (Optional but helpful) – avoid stale JSON in preview
[[headers]]
for = "/data/guide.json"
[headers.values]
Cache-Control = "no-store, max-age=0"
